services:
  - type: web
    name: friends-bills-backend
    env: node
    plan: free
    buildCommand: "npm ci"
    startCommand: "npm start"
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_ORIGIN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: "8080"
